server:
  port: 8085

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

spring:
  application:
    name: order-service


  profiles:
    active:
      - stage

  #  application:
  #    name: product
  #
  #  config:
  #    import:
  #    - configserver:http://localhost:8071

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: prod

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: qa


---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_preqa
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: preqa

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/shop24x7_stage?enabledTLSProtocols=TLSv1.2
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:samuel545}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: stage
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/angular-app


#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka



